install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install sbcl
  - curl -O https://beta.quicklisp.org/quicklisp.lisp
  - sbcl --load quicklisp.lisp --eval "(progn (quicklisp-quickstart:install) (quit))"
  - git clone https://github.com/xach/buildapp.git
  - cd buildapp
  - sudo make install

script:
  - make

notifications:
  email: false
